# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
      kernelModules = [ "amdgpu" ];
    };
    kernelModules = [ "amdgpu" "kvm-amd" ];
    kernelParams = [ "amd_iommu=on" "amd_pstate=guided" ]; # enable iGPU accelerated VMs and schedutil governor
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0f4u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware = {
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    amdgpu = {
      initrd.enable = true;  # Include AMD GPU drivers in the initrd
      opencl.enable = true;  # For OpenCL support
      amdvlk.enable = true;  # For AMD Vulkan driver
    };

    # For OpenCL support
    graphics.extraPackages = [
      pkgs.rocmPackages.clr.icd
    ];

    #pulseaudio = {
    #  enable = true;
    #  support32Bit = true;
    #  package = pkgs.pulseaudioFull;
    #  extraConfig = "load-module module-switch-on-connect";
    #};
  };

  environment.systemPackages = with pkgs; [
    clinfo
    vulkan-tools  # For vulkaninfo and vkcube
    rocmPackages.rocminfo
    rocmPackages.rocm-smi
    libva-utils   # For testing VA-API (vainfo)
  ];

  environment.variables = {
    HSA_OVERRIDE_GFX_VERSION = "11.0.3";  # Ensure this matches your GPU’s supported ROCm version
    AMDGPU_TCL_FORCE=1;
  };

  # To force a specific Vulkan ICD (optional)
  # environment.variables.AMD_VULKAN_ICD = "RADV";  # To force radv instead of amdvlk

  services.xserver.videoDrivers = [ "amdgpu" ];
}
