# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "usb_storage"
        "sd_mod"
        "sdhci_pci"
      ];
      kernelModules = [ 
        # amdgpu loads automatically, only add here if you need early KMS for Plymouth
        # "amdgpu"
        # VFIO modules for GPU passthrough (if needed in future)
        # "vfio_pci"
        # "vfio"
        # "vfio_iommu_type1"
      ];
    };
    kernelModules = [
      "amdgpu"
      "kvm-amd"
    ];
    kernelParams = [
      # IOMMU for virtualization and potential passthrough
      "amd_iommu=on"
      "iommu=pt"
      # CPU power management
      "amd_pstate=active"
      # AMD GPU optimizations
      "amdgpu.ppfeaturemask=0xffffffff"
      "amdgpu.dc=1"
      "amdgpu.dpm=1"
      "amdgpu.gpu_recovery=1"
      # Deep sleep support
      "mem_sleep_default=deep"
    ];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0f4u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware = {
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    
    # AMD GPU configuration - Minimal setup for modern integrated GPUs
    # Based on community consensus: hardware.graphics.enable is all you need for basic usage
    # Mesa RADV (Vulkan), OpenGL, and VA-API are included automatically
    graphics = {
      enable = true;
      enable32Bit = true;
      # Only add OpenCL if you need it for compute workloads (AI/ML, Blender, etc.)
      extraPackages = with pkgs; [
        rocmPackages.clr.icd  # OpenCL support
      ];
    };

    # Optional: Enable OpenCL system-wide (only if needed)
    amdgpu.opencl.enable = true;

    #pulseaudio = {
    #  enable = true;
    #  support32Bit = true;
    #  package = pkgs.pulseaudioFull;
    #  extraConfig = "load-module module-switch-on-connect";
    #};
  };

  # Diagnostic and monitoring tools
  environment.systemPackages = with pkgs; [
    # Verification tools
    glxinfo        # Check OpenGL: glxinfo | grep "OpenGL renderer"
    vulkan-tools   # Check Vulkan: vulkaninfo
    clinfo         # Check OpenCL: clinfo
    libva-utils    # Check VA-API: vainfo
    
    # Monitoring tools
    radeontop      # Monitor AMD GPU usage
    amdgpu_top     # Alternative GPU monitor
  ];

  environment.variables = {
    # VA-API driver for video acceleration (hardware decode/encode)
    LIBVA_DRIVER_NAME = "radeonsi";
    
    # Force RADV over AMDVLK if both are present (RADV is better for modern cards)
    AMD_VULKAN_ICD = "RADV";
  };

  # Let NixOS use the default "modesetting" driver (preferred over "amdgpu" driver)
  # The amdgpu kernel module will still be used automatically
  # services.xserver.videoDrivers is intentionally not set here
  
  # Fix AMD GPU performance - TLP sometimes locks GPU in low mode
  # This service ensures GPU is in auto mode on boot and after TLP starts
  systemd.services.amdgpu-performance-fix = {
    description = "Set AMD GPU to auto performance level (fix TLP override)";
    wantedBy = [ "multi-user.target" ];
    after = [ "multi-user.target" "tlp.service" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = "${pkgs.bash}/bin/bash -c 'sleep 2 && echo auto > /sys/class/drm/card*/device/power_dpm_force_performance_level 2>/dev/null || true'";
    };
  };
  
  # Virtualization support
  virtualisation = {
    libvirtd.enable = lib.mkDefault false;
    spiceUSBRedirection.enable = lib.mkDefault false;
  };
}
