# Background
image=~/.current_wallpaper
scaling=fill
color=1d2021

# Blur
effect-blur=7x3
effect-vignette=0.5:0.5

# Clock
clock
datestr=%A, %B %e
timestr=%I:%M %p
font=Inter

# Colors (Gruvbox)
inside-color=3c383680
inside-clear-color=28282880
inside-caps-lock-color=28282880
inside-ver-color=28282880
inside-wrong-color=28282880

ring-color=83a598
ring-clear-color=282828
ring-caps-lock-color=fe8019
ring-ver-color=83a598
ring-wrong-color=fb4934

key-hl-color=b8bb26
bs-hl-color=fb4934

line-color=00000000
line-clear-color=00000000
line-caps-lock-color=00000000
line-ver-color=00000000
line-wrong-color=00000000

separator-color=00000000

text-color=ebdbb2
text-clear-color=ebdbb2
text-caps-lock-color=fe8019
text-ver-color=ebdbb2
text-wrong-color=fb4934

# Input
show-failed-attempts
indicator-radius=100
indicator-thickness=2

# Hide cursor
hide-keyboard-layout
